version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: cardsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports: ["3306:3306"]
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["--appendonly", "yes"]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command:
      - start-dev
      - --import-realm
      - --http-port=8081
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8081:8081"

  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - kafka-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  app:
    build: .
    container_name: hyperativa-api
    depends_on:
      - mysql
      - redis
      - keycloak
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cardsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_REDIS_HOST: redis
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8081/realms/hyperativa
      KEYCLOAK_CLIENT_ID: api-client
      KEYCLOAK_SECRET: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"

volumes:
  mysql_data: