server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always

logging:
  level:
    br.com.hellyson: INFO
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%logger{36}){cyan} - %msg%n"

spring:
  application:
    name: hyperativa-api
  main:
    banner-mode: console
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cardsdb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 20000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/hyperativa}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: card-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      retry:
        max-attempts: 5
        backoff:
          delay: 1000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 10
      retry-backoff-ms: 500
    listener:
      ack-mode: batch
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID:api-client}
  client-secret: ${KEYCLOAK_SECRET:123456}

app:
  aes:
    key: "1234567890123456"