server:
  port: 8080

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  write:
    category: http
    level: INFO
  format:
    style: http
  filter:
    enabled: true
  obfuscate:
    headers:
      Authorization: true
    body:
      password: true

spring:
  application:
    name: hyperativa-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cardsdb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/hyperativa}
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: 6379
    timeout: 60000
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: card-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: batch

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID:api-client}
  client-secret: ${KEYCLOAK_SECRET:123456}

app:
  aes:
    key: "1234567890123456"